namespace ProShine_Script_Creator
{
    internal class MapNames
    {
        public static string[] KantoMaps { get; set; } =
        {
            "Berry Tower Reception Kanto",
            "Bike Road House 1f",
            "Bike Road Stop 1f",
            "Bike Road Stop",
            "Bills House",
            "Celadon City Subway",
            "Celadon City",
            "Celadon Gamecorner Prize Center",
            "Celadon Gamecorner Stairs",
            "Celadon House",
            "Celadon Mart 1",
            "Celadon Mart 2",
            "Celadon Mart 3",
            "Celadon Mart 4",
            "Celadon Mart 5",
            "Celadon Mart 6",
            "Celadon Mart Elevator",
            "Celadon Office 1F",
            "Celadon Office 2F",
            "Celadon Office 3F",
            "Celadon Office Elevator 1",
            "Celadon Office Elevator 2",
            "Celadon Office Roof Top",
            "CeladonGym",
            "Cerulean City Bike Shop",
            "Cerulean City Subway",
            "Cerulean City",
            "Cerulean Cave 1F",
            "Cerulean Cave 2F",
            "Cerulean Cave B1F",
            "Cerulean Gym",
            "Cerulean House 1",
            "Cerulean House 2",
            "Cerulean House 3",
            "Cerulean House 4",
            "Cerulean House 5 2f",
            "Cerulean House 5",
            "Cerulean House 6",
            "Cerulean Pokemart",
            "Cinnabar Gym B1F",
            "Cinnabar Gym",
            "Cinnabar Island",
            "Cinnabar Lab Room 1",
            "Cinnabar Lab Room 2",
            "Cinnabar Lab Room 3",
            "Cinnabar Lab",
            "Cinnabar Pokemart",
            "Cinnabar mansion 1",
            "Cinnabar mansion 2",
            "Cinnabar mansion 3",
            "Cinnabar mansion B1F",
            "Diamond Domain 1F",
            "Diamond Domain B1F",
            "Digletts Cave Entrance 1",
            "Digletts Cave Entrance 2",
            "Digletts Cave",
            "Fisherman House - Vermilion Top",
            "Fisherman House - Vermilion",
            "Fuchsia City Stop House",
            "Fuchsia City Subway",
            "Fuchsia City",
            "Fuchsia Gym",
            "Fuchsia House 1",
            "Fuchsia Pokemart",
            "Golds Gym Vitamin Shop",
            "Golds Gym",
            "Guild House",
            "Hall Of Fame B1F",
            "Hall Of Fame B2F",
            "Hall Of Fame",
            "Indigo Plateau Center Johto",
            "Indigo Plateau Center",
            "Indigo Plateau",
            "Item Maniac House",
            "Jail",
            "Kanto Daycare",
            "Kanto Safari Zone Area 1 Building 1",
            "Know It All Mans Room",
            "Lavender Pokemart",
            "Lavender Town Costume Mart 2",
            "Lavender Town Costume Mart",
            "Lavender Town House",
            "Lavender Town Subway",
            "Lavender Town Volunteer House",
            "Lavender Town",
            "Love Island",
            "Love Island Ferry",
            "Move Deleter House",
            "Mt. Moon 1F",
            "Mt. Moon B1F",
            "Mt. Moon B2F",
            "Mt. Moon Exit",
            "Mt. Silver 1F",
            "Mt. Silver 2F",
            "Mt. Silver 3F",
            "Mt. Silver Expert Belt",
            "Mt. Silver Exterior",
            "Mt. Silver Lower Mountainside",
            "Mt. Silver Pokecenter",
            "Mt. Silver Summit",
            "Mt. Silver Upper Mountainside",
            "New Bark Town",
            "Oaks Lab",
            "Pallet Town",
            "Pewter City Subway",
            "Pewter City",
            "Pewter Gym",
            "Pewter House 1",
            "Pewter House 2",
            "Pewter Museum",
            "Pewter Pokemart",
            "Player Bedroom Pallet",
            "Player House Pallet",
            "Pokecenter Celadon",
            "Pokecenter Cerulean",
            "Pokecenter Cinnabar",
            "Pokecenter Fuchsia",
            "Pokecenter Lavender",
            "Pokecenter Love Island",
            "Pokecenter Pewter",
            "Pokecenter Route 10",
            "Pokecenter Route 3",
            "Pokecenter Saffron",
            "Pokecenter Trainers Valley",
            "Pokecenter Vermilion",
            "Pokecenter Viridian",
            "Pokemon Club",
            "Pokemon League Reception Gate",
            "Pokemon Tower 1F",
            "Pokemon Tower 2F",
            "Pokemon Tower 3F",
            "Pokemon Tower 4F",
            "Pokemon Tower 5F",
            "Pokemon Tower 6F",
            "Pokemon Tower 7F",
            "Pokemon Tower B1",
            "Pokemon Tower B10",
            "Pokemon Tower B11",
            "Pokemon Tower B12",
            "Pokemon Tower B13",
            "Pokemon Tower B14",
            "Pokemon Tower B15",
            "Pokemon Tower B16",
            "Pokemon Tower B17",
            "Pokemon Tower B18",
            "Pokemon Tower B19",
            "Pokemon Tower B2",
            "Pokemon Tower B20",
            "Pokemon Tower B21",
            "Pokemon Tower B22",
            "Pokemon Tower B23",
            "Pokemon Tower B24",
            "Pokemon Tower B29",
            "Pokemon Tower B3",
            "Pokemon Tower B4",
            "Pokemon Tower B6",
            "Pokemon Tower B7",
            "Pokemon Tower B8",
            "Pokemon Tower B9",
            "Pokemon Tower Underground",
            "Power Plant",
            "Private Resort",
            "Psychic House",
            "Rivals House 2F",
            "Rivals House",
            "Rock Tunnel 1",
            "Rock Tunnel 2",
            "Route 1 Stop House",
            "Route 1",
            "Route 10",
            "Route 11 Stop House 1f",
            "Route 11 Stop House",
            "Route 11",
            "Route 12 House",
            "Route 12",
            "Route 13",
            "Route 14",
            "Route 15 Stop House",
            "Route 15",
            "Route 16 Stop House",
            "Route 16 house",
            "Route 16",
            "Route 17",
            "Route 18",
            "Route 19",
            "Route 2 House",
            "Route 2 Stop",
            "Route 2 Stop2",
            "Route 2 Stop3",
            "Route 20",
            "Route 21",
            "Route 22",
            "Route 24",
            "Route 25",
            "Route 26 House 2",
            "Route 26 House1",
            "Route 26",
            "Route 27 House1",
            "Route 27",
            "Route 28 House",
            "Route 28",
            "Route 2",
            "Route 3",
            "Route 4",
            "Route 5 Stop House",
            "Route 5",
            "Route 6 Stop House",
            "Route 6",
            "Route 7 Stop House",
            "Route 7",
            "Route 8 Stop House",
            "Route 8",
            "Route 9",
            "Safari Area 1",
            "Safari Area 2",
            "Safari Area 3",
            "Safari Effort Wald 1",
            "Safari Effort Wald 2",
            "Safari Entrance",
            "Safari Exclusive",
            "Safari House 2",
            "Safari House 3",
            "Safari House 4",
            "Safari Stop",
            "Saffron City Station Floor 2",
            "Saffron City Station",
            "Saffron City Subway",
            "Saffron City",
            "Saffron Dojo",
            "Saffron Gym",
            "Saffron House Bottom",
            "Saffron House Top",
            "Saffron Pokemart",
            "Seafoam 1F",
            "Seafoam B1F",
            "Seafoam B2F",
            "Seafoam B3F",
            "Seafoam B4F",
            "SecretHouse",
            "Silph Co 10F",
            "Silph Co 11F",
            "Silph Co 1F",
            "Silph Co 2F",
            "Silph Co 3F",
            "Silph Co 4F",
            "Silph Co 5F",
            "Silph Co 6F",
            "Silph Co 7F",
            "Silph Co 8F",
            "Silph Co 9F",
            "Silph Co Elevator",
            "Tohjo Falls",
            "Trainers Valley",
            "Trainers Valley Station",
            "Trainers Valley Station Floor 2",
            "Trainers Valley Stop",
            "Underground House 1",
            "Underground House 2",
            "Underground House 3",
            "Underground House 4",
            "Underground1",
            "Underground2",
            "Vermilion City Subway",
            "Vermilion City",
            "Vermilion Gym",
            "Vermilion House 1",
            "Vermilion House A",
            "Vermilion House B",
            "Vermilion House C",
            "Vermilion House D Top",
            "Vermilion House D",
            "Vermilion House E",
            "Vermilion Pokemart",
            "VermilionHouse2Bottom",
            "VermilionHouse2Top",
            "Victory Road Kanto 1F",
            "Victory Road Kanto 2F",
            "Victory Road Kanto 3F",
            "Viridian City House 1",
            "Viridian City House 2",
            "Viridian City School Underground",
            "Viridian City School",
            "Viridian City Subway",
            "Viridian City",
            "Viridian Forest",
            "Viridian Gym 2",
            "Viridian Maze",
            "Viridian Pokemart",
        };

        public static string[] SeviiMaps { get; set; } =
        {

            "Altering Cave",
            "Berry Forest",
            "Bond Bridge",
            "Canyon Entrance",
            "Cape Brink Move Tutor House",
            "Cape Brink",
            "Chrono Cross",
            "Dotted Hole B1F",
            "Dotted Hole B2F",
            "Dotted Hole B3F",
            "Dotted Hole B4F",
            "Dotted Hole B5F",
            "Dotted Hole Entrance",
            "Dotted Hole Exit",
            "Ember Spa",
            "Five Island Ferry",
            "Five Island House 1",
            "Five Island House 2",
            "Five Island Rocket Hideout",
            "Five Island",
            "Five Isle Meadow",
            "Four Island Daycare",
            "Four Island Ferry",
            "Four Island House 1",
            "Four Island House 2",
            "Four Island House 3",
            "Four Island",
            "Green Path Cave B1F",
            "Green Path Cave B2F",
            "Green Path Cave Entrance",
            "Green Path Cave Exit",
            "Green Path",
            "Icefall Back Cave",
            "Icefall Cave 1F",
            "Icefall Cave B1F",
            "Icefall Cave Entrance",
            "Joyful Game Corner",
            "Kindle Road",
            "Lost Cave 1F1",
            "Lost Cave 1F10",
            "Lost Cave 1F11",
            "Lost Cave 1F12",
            "Lost Cave 1F13",
            "Lost Cave 1F14",
            "Lost Cave 1F2",
            "Lost Cave 1F3",
            "Lost Cave 1F4",
            "Lost Cave 1F5",
            "Lost Cave 1F6",
            "Lost Cave 1F7",
            "Lost Cave 1F8",
            "Lost Cave 1F9",
            "Lost Cave Entrance",
            "Lost Cave",
            "Mart Four Island",
            "Mart Seven Island",
            "Mart Three Island",
            "Memorial Pillar",
            "Mt. Ember Ruby Path 1F",
            "Mt. Ember Ruby Path B1F",
            "Mt. Ember Ruby Path B2F",
            "Mt. Ember Ruby Path B3F",
            "Mt. Ember Ruby Path B4F",
            "Mt. Ember Ruby Path B5F",
            "Mt. Ember Summit Path 1F",
            "Mt. Ember Summit Path 2F",
            "Mt. Ember Summit Path 3F",
            "Mt. Ember",
            "One Island Ferry",
            "One Island House 1",
            "One Island House 2",
            "One Island",
            "Outcast Island",
            "Pokecenter Five Island",
            "Pokecenter Four Island",
            "Pokecenter One Island",
            "Pokecenter Seven Island",
            "Pokecenter Six Island",
            "Pokecenter Three Island",
            "Pokecenter Two Island",
            "Pokemart Six Island",
            "Resort Gorgeous",
            "Resort House 1",
            "Resort House 2",
            "Ruin Valley",
            "Sapphire Room",
            "Sevault Canyon House 1",
            "Sevault Canyon",
            "Seven Island Ferry",
            "Seven Island House 1",
            "Seven Island",
            "Six Island Ferry Reception",
            "Six Island Ferry",
            "Six Island House 1",
            "Six Island House 2",
            "Six Island",
            "SpringDell Hideout Lab",
            "SpringDell Hideout",
            "Tanoby Key",
            "Tanoby Ruins Dilford Chamber",
            "Tanoby Ruins Liptoo Chamber",
            "Tanoby Ruins Monean Chamber",
            "Tanoby Ruins Scufib Chamber",
            "Tanoby Ruins Viapois Chamber",
            "Tanoby Ruins Weepth Chamber",
            "Tanoby Ruins",
            "Three Island Ferry",
            "Three Island House 1",
            "Three Island House 2",
            "Three Island House 3",
            "Three Island House 4",
            "Three Island House 5",
            "Three Island",
            "Three Isle Path",
            "Three Isle Port",
            "Trainer Tower",
            "Treasure Beach",
            "Two Island Ferry",
            "Two Island House",
            "Two Island",
            "Water Labyrinth",
            "Water Path House 1",
            "Water Path House 2",
            "Water Path House 3",
            "Water Path",
        };

        public static string[] JohtoMaps { get; set; } =
        {
            "Abandoned Desert Village",
            "Amazon Forest Entrance",
            "Amazon Forest",
            "Azalea House1",
            "Azalea Kurts House",
            "Azalea Pokemart",
            "Azalea Town Gym",
            "Azalea Town Subway",
            "Azalea Town",
            "Battle Road House",
            "Battle Road",
            "Battle Tower Entrance",
            "Bell Tower Barrier Station 1F",
            "Bell Tower Barrier Station B1F",
            "Bell Tower Floor 10",
            "Bell Tower Floor 2",
            "Bell Tower Floor 3",
            "Bell Tower Floor 4",
            "Bell Tower Floor 5",
            "Bell Tower Floor 6",
            "Bell Tower Floor 7",
            "Bell Tower Floor 8",
            "Bell Tower Floor 9",
            "Bell Tower Roof",
            "Bell Tower",
            "Blackthorn City Dragon Club 1F",
            "Blackthorn City Dragon Club 2F",
            "Blackthorn City Dragon Club 3F",
            "Blackthorn City Gym",
            "Blackthorn City House 1",
            "Blackthorn City House 2",
            "Blackthorn City House 3",
            "Blackthorn City Pokemart",
            "Blackthorn City Subway",
            "Blackthorn City",
            "Burned Tower Floor 2",
            "Burned Tower Top Floor",
            "Cherrygrove City House 1",
            "Cherrygrove City House 2",
            "Cherrygrove City House 3",
            "Cherrygrove City Subway",
            "Cherrygrove City",
            "Cianwood City Gym",
            "Cianwood City",
            "Cianwood House 1",
            "Cianwood House 2",
            "Cianwood House 3",
            "Cianwood House 4",
            "Cianwood Shop",
            "Cliff Cave 1F",
            "Cliff Cave 2F",
            "Cliff Cave B1F",
            "Cliff Edge Gate",
            "Dark Cave North",
            "Dark Cave South",
            "Desert Cave",
            "Desert Lagoon",
            "Dock Island",
            "Dragons Den B1F",
            "Dragons Den Entrance",
            "Dragons Den",
            "Ecruteak City Costume Mart",
            "Ecruteak City House 1",
            "Ecruteak City House 2",
            "Ecruteak City Subway",
            "Ecruteak City",
            "Ecruteak Dance Theater",
            "Ecruteak Gym",
            "Ecruteak Mart",
            "Ecruteak Stop House 1",
            "Ecruteak Stop House 2",
            "Glitter Lighthouse 1F",
            "Glitter Lighthouse 2F",
            "Glitter Lighthouse 3F",
            "Glitter Lighthouse 4F",
            "Glitter Lighthouse 5F",
            "Goldenrod City Bike Shop",
            "Goldenrod City Bills House",
            "Goldenrod City Flower Shop",
            "Goldenrod City Fortune Teller Tent",
            "Goldenrod City Game Corner",
            "Goldenrod City Gym",
            "Goldenrod City House 1",
            "Goldenrod City House 2",
            "Goldenrod City Station Floor 2",
            "Goldenrod City Station",
            "Goldenrod City Subway",
            "Goldenrod City",
            "Goldenrod Global Station",
            "Goldenrod Mart 1",
            "Goldenrod Mart 2",
            "Goldenrod Mart 3",
            "Goldenrod Mart 4",
            "Goldenrod Mart 5",
            "Goldenrod Mart 6",
            "Goldenrod Mart B1F",
            "Goldenrod Mart Elevator",
            "Goldenrod Radio Station Floor 1",
            "Goldenrod Underground Entrance Bottom",
            "Goldenrod Underground Entrance Top",
            "Goldenrod Underground Path",
            "Ice Path 1F",
            "Ice Path B1F",
            "Ice Path B2F",
            "Ice Path B3F",
            "Ilex Forest Stop House",
            "Ilex Forest",
            "Item Maniac Johto",
            "Johto Safari Entrance",
            "Johto Safari Zone Lobby",
            "Lake of Rage House 1",
            "Lake of Rage House 2",
            "Lake of Rage",
            "Mahogany Town Gym",
            "Mahogany Town House",
            "Mahogany Town Shop",
            "Mahogany Town Subway",
            "Mahogany Town",
            "Mart Cherrygrove City",
            "Miltank Barn",
            "Mt. Mortar 1F",
            "Mt. Mortar B1F",
            "Mt. Mortar Lower Cave",
            "Mt. Mortar Upper Cave",
            "National Park Stop House 1",
            "National Park Stop",
            "National Park",
            "New Bark Town House 2",
            "New Bark Town House",
            "New Bark Town Player House Bedroom",
            "New Bark Town Player House",
            "Olivine Cafe",
            "Olivine City Gym",
            "Olivine City Subway",
            "Olivine City",
            "Olivine House 1",
            "Olivine House 2",
            "Olivine House 3",
            "Olivine Pokecenter",
            "Olivine Pokemart",
            "Pokecenter Azalea",
            "Pokecenter Blackthorn",
            "Pokecenter Cherrygrove City",
            "Pokecenter Cianwood",
            "Pokecenter Ecruteak",
            "Pokecenter Goldenrod",
            "Pokecenter Mahogany",
            "Pokecenter Route 32",
            "Pokecenter Route 48",
            "Pokecenter Violet City",
            "Professor Elms House",
            "Professor Elms Lab",
            "Route 29 Stop House",
            "Route 29",
            "Route 30 House 1",
            "Route 30 House 2",
            "Route 30",
            "Route 31",
            "Route 32",
            "Route 33",
            "Route 34 Stop House",
            "Route 34",
            "Route 35 Stop House",
            "Route 35",
            "Route 36 Stop",
            "Route 36",
            "Route 37",
            "Route 38",
            "Route 39 House",
            "Route 39",
            "Route 40",
            "Route 41",
            "Route 42",
            "Route 43",
            "Route 44",
            "Route 45",
            "Route 46",
            "Route 47",
            "Route 48",
            "Ruins Of Alph Stop House 1",
            "Ruins Of Alph Stop House",
            "Ruins Of Alph",
            "Ruins Research Center",
            "Safari Johto Grass and Swamp Zone",
            "Safari Johto Mountain Zone",
            "Safari Johto Snow Zone",
            "Safari Johto Wet Zone",
            "Slowpoke Well L1",
            "Slowpoke Well",
            "Sprout Tower F1",
            "Sprout Tower F2",
            "Sprout Tower F3",
            "Underground Warehouse",
            "Union Cave 1F",
            "Union Cave B1F",
            "Union Cave B2F",
            "Violet City Gym Entrance",
            "Violet City Gym",
            "Violet City House 1",
            "Violet City House 2",
            "Violet City Pokemart",
            "Violet City School",
            "Violet City Stop House",
            "Violet City Subway",
            "Violet City",
            "Whirl Islands 1F NorthEast",
            "Whirl Islands 1F NorthWest",
            "Whirl Islands 1F SouthEast",
            "Whirl Islands 1F SouthWest",
            "Whirl Islands B1F",
            "Whirl Islands B2F",
            "Whirl Islands B3F",
            "Whirl Islands B4F",
        };

        public static string[] HoennMaps { get; set; } =
        {
            "Abandoned Ship 1F Room 1",
            "Abandoned Ship 1F Room 2",
            "Abandoned Ship 1F",
            "Abandoned Ship B1F Room 1",
            "Abandoned Ship B1F Room 2",
            "Abandoned Ship B1F Room 3",
            "Abandoned Ship B1F Room 4",
            "Abandoned Ship B1F",
            "Abandoned Ship Exterior",
            "Ancient Tomb",
            "Backdoor House 1",
            "Backdoor House 2",
            "Berry Masters House",
            "Cable Car Station 1",
            "Cable Car Station 2",
            "Captains Office",
            "Cave Of Steel 1F",
            "Cave Of Steel 2F",
            "Cave of Origin 1F",
            "Cave of Origin B1F",
            "Cave of Origin B2F",
            "Cave of Origin B3F",
            "Cave of Origin Entrance",
            "Cutter House",
            "Cycle Road Stop House 1",
            "Cycle Road Stop House 2",
            "Desert Ruins",
            "Desert Underpass Entrance",
            "Devon Corporation 1F",
            "Devon Corporation 2F",
            "Devon Corporation 3F",
            "Dewford Town Gym",
            "Dewford Town House 1",
            "Dewford Town House 2",
            "Dewford Town House 3",
            "Dewford Town",
            "Eastern House 1",
            "Eastern House 2",
            "Eastern House 3",
            "Ever Grande City",
            "Fallarbor House",
            "Fallarbor Town",
            "Feral Site",
            "Fiery Path",
            "Fortree City",
            "Fortree Gym",
            "Fortree House 1",
            "Fortree House 2",
            "Fortree House 3",
            "Fortree House 4",
            "Fortree House 5",
            "Fortree House 6",
            "Fortree Mart",
            "Fossil Maniac House",
            "Glacial Site",
            "Granite Cave 1F2",
            "Granite Cave 1F",
            "Granite Cave B1F",
            "Granite Cave B2F",
            "Haunted Site",
            "Historical Site",
            "Hoenn Safari Zone Area 1",
            "Hoenn Safari Zone Area 2",
            "Hoenn Safari Zone Area 3",
            "Hoenn Safari Zone Area 4",
            "Hoenn Safari Zone Area 5",
            "Hoenn Safari Zone Area 6",
            "Hoenn Safari Zone Lobby",
            "Island Cave",
            "Jagged Pass",
            "Jura Cave",
            "Jura Pass",
            "Lab Littleroot Town",
            "Lavaridge Mart",
            "Lavaridge Town Gym 1F",
            "Lavaridge Town Gym B1F",
            "Lavaridge Town Herb Shop",
            "Lavaridge Town House",
            "Lavaridge Town",
            "Leev Town Entrance",
            "Leev Town Port",
            "Leev Town",
            "Lilycove CIty House 3",
            "Lilycove City Harbor",
            "Lilycove City House 1",
            "Lilycove City House 2",
            "Lilycove City House 4",
            "Lilycove City House 5",
            "Lilycove City",
            "Lilycove Department Store 1F",
            "Lilycove Department Store 2F",
            "Lilycove Department Store 3F",
            "Lilycove Department Store 4F",
            "Lilycove Department Store 5F",
            "Lilycove Department Store Elevator",
            "Lilycove Department Store Roof",
            "Lilycove Motel 1F",
            "Lilycove Motel 2F",
            "Lilycove Museum 1F",
            "Lilycove Museum 2F",
            "Littleroot Town Truck",
            "Littleroot Town",
            "Low Tide Entrance Room",
            "Marine Cave End",
            "Marine Cave Entrance",
            "Mart Fallarbor Town",
            "Mart Mauville City",
            "Mart Oldale Town",
            "Mart Petalburg City",
            "Mart Rustboro City",
            "Mart Slateport",
            "Mauville City Game Corner",
            "Mauville City Gym",
            "Mauville City House 1",
            "Mauville City House 2",
            "Mauville City Stop House 1",
            "Mauville City Stop House 2",
            "Mauville City Stop House 3",
            "Mauville City Stop House 4",
            "Mauville City",
            "Meteor Falls 1F 2R",
            "Meteor Falls B1F 2R",
            "Meteor falls 1F 1R",
            "Meteor falls B1F 1R",
            "Mineral Site",
            "Moon 1F",
            "Moon 2F",
            "Moon B1F",
            "Moon",
            "Mossdeep City House",
            "Mossdeep City Space Center 1F",
            "Mossdeep City Space Center 2F",
            "Mossdeep City",
            "Mossdeep Gym",
            "Mossdeep Pokemart",
            "Mt. Chimney",
            "Mt. Pyre 1F",
            "Mt. Pyre 2F",
            "Mt. Pyre 3F",
            "Mt. Pyre 4F",
            "Mt. Pyre Exterior",
            "Mt. Pyre Summit",
            "Natural Site",
            "New Mauville Entrance",
            "New Mauville",
            "Old Lady House",
            "Oldale Town House 1",
            "Oldale Town House 2",
            "Oldale Town",
            "Pacifidlog Town House 1",
            "Pacifidlog Town House 2",
            "Pacifidlog Town House 3",
            "Pacifidlog Town House 4",
            "Pacifidlog Town House 5",
            "Pacifidlog Town",
            "Petalburg City Gym",
            "Petalburg City House 1",
            "Petalburg City House 2",
            "Petalburg City Wallys House",
            "Petalburg City",
            "Petalburg Maze",
            "Petalburg Woods",
            "Player Bedroom Littleroot Town",
            "Player House Littleroot Town",
            "Pokeblock Enthusiasts House",
            "Pokecenter Dewford Town",
            "Pokecenter Eastern Peak",
            "Pokecenter Ever Grande City",
            "Pokecenter Fallarbor Town",
            "Pokecenter Fortree City",
            "Pokecenter Lavaridge Town",
            "Pokecenter Leev Town",
            "Pokecenter Lilycove City",
            "Pokecenter Mauville City",
            "Pokecenter Mossdeep City",
            "Pokecenter Oldale Town",
            "Pokecenter Pacifidlog Town",
            "Pokecenter Petalburg City",
            "Pokecenter Rustboro City",
            "Pokecenter Slateport",
            "Pokecenter Sootopolis City",
            "Pokecenter Verdanturf",
            "Pokecenter Western Peak",
            "Pokemon League Hoenn",
            "Pokemon Trainers School",
            "Prof. Birch Bedroom",
            "Prof. Birch House",
            "Professor Cozmo House",
            "Route 101",
            "Route 102",
            "Route 103",
            "Route 104 House",
            "Route 104 Sailor House",
            "Route 104",
            "Route 105",
            "Route 106",
            "Route 107",
            "Route 108",
            "Route 109 House",
            "Route 109",
            "Route 110",
            "Route 111 Desert",
            "Route 111 House 1",
            "Route 111 North",
            "Route 111 South",
            "Route 112",
            "Route 113",
            "Route 114 House",
            "Route 114",
            "Route 115",
            "Route 116 House",
            "Route 116",
            "Route 117",
            "Route 118",
            "Route 119A",
            "Route 119B House",
            "Route 119B",
            "Route 120",
            "Route 121",
            "Route 122",
            "Route 123",
            "Route 124 Underwater",
            "Route 124",
            "Route 125",
            "Route 126 Underwater",
            "Route 126",
            "Route 127 Underwater",
            "Route 127",
            "Route 128 Underwater",
            "Route 128",
            "Route 129 Underwater",
            "Route 129",
            "Route 130 Underwater",
            "Route 130",
            "Route 131",
            "Route 132",
            "Route 133",
            "Route 134",
            "Rustboro City Building 1 1F",
            "Rustboro City Building 1 2F",
            "Rustboro City Building 1 3F",
            "Rustboro City Building 2 1F",
            "Rustboro City Building 2 2F",
            "Rustboro City Gym",
            "Rustboro City House 1",
            "Rustboro City House 2",
            "Rustboro City House 3",
            "Rustboro City",
            "Rusturf Tunnel",
            "Rydels Cycles",
            "Secret Base Boy House",
            "Secret Underwater Cavern",
            "Sky Pillar 1F",
            "Sky Pillar 2F",
            "Sky Pillar 3F",
            "Sky Pillar 4F",
            "Sky Pillar 5F",
            "Sky Pillar 6F",
            "Sky Pillar Entrance Cave 1F",
            "Sky Pillar Entrance",
            "Slateport City House 1",
            "Slateport City House 2",
            "Slateport City",
            "Slateport Harbor",
            "Slateport Museum 1F",
            "Slateport Museum 2F",
            "Slateport Shipyard 1F",
            "Slateport Shipyard 2F",
            "Sootopolis City Gym 1F",
            "Sootopolis City House 1",
            "Sootopolis City House 2",
            "Sootopolis City House 3",
            "Sootopolis City House 4",
            "Sootopolis City House 5",
            "Sootopolis City House 6",
            "Sootopolis City House 7",
            "Sootopolis City House 8",
            "Sootopolis City Underwater",
            "Sootopolis City",
            "Sootopolis Mart",
            "Stevens House",
            "Storage Unit",
            "Team Aqua Hideout  Entrance",
            "Team Aqua Hideout 1F",
            "Team Aqua Hideout B1F",
            "Team Aqua Hideout B2F",
            "Team Aqua Hideout Warp Hallway",
            "Terra Cave End",
            "Terra Cave Entrance",
            "Transmat Station",
            "Treasure Hunter House",
            "Trick House",
            "Valley Of Steel Eastern Peak",
            "Valley Of Steel Entrance",
            "Valley Of Steel Western Peak",
            "Valley Of Steel",
            "Verdanturf Battle Tent",
            "Verdanturf House 1",
            "Verdanturf House 2",
            "Verdanturf House 3",
            "Verdanturf Mart",
            "Verdanturf Town",
            "Victory Road Hoenn 1F",
            "Victory Road Hoenn B1F",
            "Victory Road Hoenn B2F",
            "Weather Institute 1F",
            "Weather Institute 2F",
            "Western House 1",
            "Western House 2",
            "Western House 3",
            "Western House 4",
        };

        public static string[] EventMaps { get; set; } =
        {
            "Kalijodo Path",
            "Kalijodo Cave B1F",
            "Kalijodo Cave B2F",
            "Kalijodo Cave Entrance",
            "Kalijodo Lake",
            "Pokecenter Vulcanic Town",
            "Vulcan Island shore",
            "Vulcan Path",
            "Vulcan Forest",
            "Vulcanic Town",
            "Cryofrost Brink",
            "Cryofrost Path",
            "Cryofrost Path Costume Mart",
            "Cryofrost Town",
            "Flake Wood",
            "Frost Valley",
            "Frozen Cave B1F",
            "Frozen Cave B2F",
            "Frozen Cave Entrance",
            "Mart Cryofrost Town",
            "Pokecenter Cryofrost Town",
            "Snowfall Valley",
            "Pokecenter Murky Town",
            "Murky Town",
            "Pokecenter Unison Mountain",
            "Unison Mountain South Summit",
            "Ghoul Swamp",
            "Cupid City",
            "Cupid City House 1",
            "Cupid City House 2",
            "Pokecenter Cupid City",
        };

        public static string[] SinnohMaps { get; set; } =
        {
            "Canalave Pokecenter",
            "Pokecenter Eterna City",
            "Pokecenter Jubilife City",
            "Pokecenter Oreburgh City",
            "Veilstone Pokecenter",
            "Celestic Pokecenter",
            "Fight Area Pokecenter",
            "Pokecenter Floaroma",
            "Pokecenter Hearthome City",
            "Pastoria Pokecenter",
            "Pokecenter Resort Area",
            "Pokecenter Sandgem Town",
            "Pokecenter Snowpoint City",
            "Solaceon Pokecenter",
            "Pokecenter Sunyshore",
            "Pokecenter Survival Area",
            "Transmat Station Sinnoh",
            "Canalave City",
            "Celestic Town",
            "Eterna City",
            "Fight Area",
            "Floaroma Town",
            "Hearthome City",
            "Jubilife City",
            "Oreburgh City",
            "Pastoria City",
            "Resort Area",
            "Sandgem Town",
            "Snowpoint City",
            "Solaceon Town",
            "Sunyshore City",
            "Survival Area",
            "Veilstone City",
            "Route 201",
            "Route 202",
            "Route 203",
            "Route 204",
            "Route 205",
            "Route 206",
            "Route 207",
            "Route 208",
            "Route 209",
            "Route 210",
            "Route 210 North",
            "Route 210 South",
            "Route 211",
            "Route 212",
            "Route 212 South",
            "Route 212 North",
            "Route 213",
            "Route 214",
            "Route 215",
            "Route 216",
            "Route 217",
            "Route 218",
            "Route 219",
            "Route 220",
            "Route 221",
            "Route 222",
            "Route 223",
            "Route 224",
            "Route 225",
            "Route 226",
            "Route 227",
            "Route 228",
            "Route 229",
            "Route 230",
            "Eterna City Stop House",
            "Route 214 Stop House",
            "Oreburgh Gate 1F",
            "Oreburgh Gate B1F",
            "Oreburgh Mine B2F 1R",
            "Oreburgh Mine B2F 2R",
            "Wayward Cave",
            "Wayward Cave Secret Area",
            "Route 206 Stop House",
            "Sendoff Spring",
            "Celestic Ruins",
            "Twinleaf Town",
            "Fuego Ironworks",
            "Eterna Forest",
            "Valley Windworks",
            "Amity Square Entrance 1",
            "Amity Square",
            "Amity Square Entrance 1",
            "Maniac Tunnel",
            "Solaceon Ruins",
            "Great Marsh",
            "Pal Park",
            "Acuity Lakefront",
            "Snowpoint Temple",
            "Seabreak Path",
            "Flower Paradise",
            "Sinnoh Victory Road 1F",
            "Sinnoh Victory Road 2F",
            "Sinnoh Victory Road 2F",
            "Sinnoh Victory Road B1F Deep",
            "Iron Island",
            "Iron Island 1F",
            "Iron Island B1F L",
            "Iron Island B1F R",
            "Iron Island B2F L",
            "Iron Island B2F R",
            "Iron Island Exit Room",
            "Lake Acuity",
            "Jubilife Trainers School",
            "Sinnoh Safari Zone",
            "Sinnoh Safari Area Zone 1",
            "Sinnoh Safari Area Zone 2",
            "Sinnoh Safari Area Zone 3",
            "Sinnoh Safari Area Zone 4",
            "Sinnoh Safari Area Zone 5",
            "High Tide Entrance Room",
            "Lake Varity",
            "Lake Valor",
            "Ravaged Path",
            "Valley Windworks Interior",
            "Lost Tower 1F",
            "Lost Tower 2F",
            "Lost Tower 3F",
            "Lost Tower 4F",
            "Mt. Coronet South",
            "Route 201 Stop House",
            "Route 202 Stop House",
            "Route 203 Stop House",
            "Route 204 Stop House",
            "Route 205 Stop House",
            "Route 206 Stop House",
            "Route 207 Stop House",
            "Route 208 Stop House",
            "Route 209 Stop House",
            "Route 210 Stop House",
            "Route 211 Stop House",
            "Route 212 Stop House",
            "Route 212 South Stop House",
            "Route 212 North Stop House",
            "Route 213 Stop House",
            "Route 214 Stop House",
            "Route 215 Stop House",
            "Route 216 Stop House",
            "Route 217 Stop House",
            "Route 218 Stop House 1",
            "Route 218 Stop House 2",
            "Route 219 Stop House",
            "Route 220 Stop House",
            "Route 221 Stop House",
            "Route 222 Stop House",
            "Route 223 Stop House",
            "Route 224 Stop House",
            "Route 225 Stop House",
            "Route 226 Stop House",
            "Route 227 Stop House",
            "Route 228 Stop House",
            "Route 229 Stop House",
            "Route 230 Stop House",
            "Canalave City Stop House",
            "Celestic Town Stop House",
            "Fight Area Stop House",
            "Floaroma Town Stop House",
            "Hearthome City Stop House 1",
            "Hearthome City Stop House 2",
            "Jubilife City Stop House",
            "Oreburgh City Stop House",
            "Pastoria City Stop House",
            "Resort Area Stop House",
            "Sandgem Town Stop House",
            "Snowpoint City Stop House",
            "Solaceon Town Stop House",
            "Sunyshore City Stop House",
            "Survival Area Stop House",
            "Veilstone City Stop House",
            "Floaroma Meadow",
            "Old Chateau 1F",
            "Old Chateau 1F 1R",
            "Old Chateau 1F 2R",
            "Old Chateau 2F",
            "Old Chateau 2F 1R",
            "Old Chateau 2F 2R",
            "Old Chateau 2F 3R",
            "Old Chateau 2F 4R",
            "Old Chateau 2F 5R",
            "Old Chateau Dining Room",
            "Eterna Galactic Building 1F",
            "Eterna Galactic Building 2F",
            "Eterna Galactic Building 3F",
            "Eterna Galactic Building 4F",
            "Mt. Coronet",
            "Team Galactic HQ",
            "Stark Mountain",
            "Mt. Coronet B1F",
            "Mt. Coronet 2F",
            "Mt. Coronet 3F",
            "Mt. Coronet 4F",
            "Mt. Coronet Snowing",
            "Mt. Coronet 5F",
            "Mt. Coronet 6F",
            "Mt. Coronet 7F",
            "Mt. Coronet Center",
            "Mt. Coronet Tunnel",
            "Mt. Coronet B1",
            "Mt. Coronet North",
            "Stark Mountain Entrance",
            "Stark Mountain Inside",
            "Snowpoint Temple 1F",
            "Snowpoint Temple B1F",
            "Snowpoint Temple B1",
            "Snowpoint Temple B2F",
            "Snowpoint Temple B2",
            "Snowpoint Temple B3F",
            "Snowpoint Temple B3",
            "Snowpoint Temple B4F",
            "Snowpoint Temple B4",
            "Snowpoint Temple B5F",
            "Snowpoint Temple B5",
            "Great Marsh",
            "Fullmoon Island",
            "Newmoon Island",
            "Turnback Cave",
            "Celestic House 1",
            "Celestic House 2",
            "Celestic House 2",
            "Celestic House 4",
            "Rowan Lab",
            "Sandgem Town House",
            "Dawn House",
            "Dawn House 1F",
            "Twinleaf Town Player House",
            "Twinleaf Town Player House 2F",
            "Twinleaf Town House 1",
            "Twinleaf Town House 2",
            "Twinleaf Town Rival House",
            "Twinleaf Town Rival House 2F",
            "Jubilife House 1",
            "Jubilife House 2",
            "Jubilife House 3",
            "Oreburgh City Gym",
            "Eterna Gym",
            "Hearthome Gym Entrance",
            "Hearthome Gym Room 1",
            "Hearthome Gym Room 2",
            "Hearthome Gym Leader Room",
            "Veilstone Gym",
            "Pastoria Gym",
            "Canalave Gym",
            "Canalave Gym 2F",
            "Canalave Gym 3F",
            "Canalave Gym 4F",
            "Snowpoint Gym",
            "SunyShore Gym",
            "SunyShore Gym 2",
            "SunyShore Gym 3",
        };
    }
}
